[package]
name = "orml-bencher"
description = "Provide macro to benchmark pallets."
repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/bencher"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
linregress = { version = "0.4.0", optional = true }
codec = { package = 'parity-scale-codec', version = "2.0.0", features = ['derive'], default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
sp-runtime-interface = { version = "3.0.0", default-features = false }
sc-executor = { version = "0.9.0", default-featues = false, optional = true }

[features]
default = ["std"]
std = [
    "linregress",
    "codec/std",
    "sp-core/std",
    "sp-std/std",
    "sp-io/std",
    "sp-runtime-interface/std",
    "sc-executor/std",
]
